const CollectionActions = {
  CREATE_COLLECTION: "CREATE_COLLECTION",
  EDIT_COLLECTION: "EDIT_COLLECTION",
  DELETE_COLLECTION: "DELETE_COLLECTION",
  FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
  FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_FAILURE: "FETCH_COLLECTIONS_FAILURE",
}

export default CollectionActions
