const CollectionsActionTypes = {
  CREATE_COLLECTION: "CREATE_COLLECTION",
  EDIT_COLLECTION: "EDIT_COLLECTION",
  REMOVE_COLLECTION: "REMOVE_COLLECTION",
  ADD_COLLECTION_SELECT_QUESTION: "ADD_COLLECTION_SELECT_QUESTION",
  EDIT_COLLECTION_SELECT_QUESTION: "EDIT_COLLECTION_SELECT_QUESTION",
  REMOVE_COLLECTION_SELECT_QUESTION: "REMOVE_COLLECTION_SELECT_QUESTION",
  EDIT_COLLECTION_SELECT_ANSWER: "EDIT_COLLECTION_SELECT_ANSWER",
}

export default CollectionsActionTypes
