const CollectionActions = {
  CREATE_COLLECTION: "CREATE_COLLECTION",
  EDIT_COLLECTION: "EDIT_COLLECTION",
  DELETE_COLLECTION: "DELETE_COLLECTION",

  ADD_SLIDE_QUIZ: "ADD_SLIDE_QUIZ",
  ADD_SLIDE_TRUE_FALSE: "ADD_SLIDE_TRUE_FALSE",
  EDIT_SLIDE: "EDIT_SLIDE",
  DUPLICATE_SLIDE: "DUPLICATE_SLIDE",
  DELETE_SLIDE: "DELETE_SLIDE",

  EDIT_OPTION: "EDIT_OPTION",
}

export default CollectionActions
