const EventHostPropertiesActions = {
  CREATE_EVENT_START: "CREATE_EVENT_START",
  CREATE_EVENT_SUCCESS: "CREATE_EVENT_SUCCESS",
  CREATE_EVENT_FAILURE: "CREATE_EVENT_FAILURE",

  START_EVENT_START: "START_EVENT_START",
  START_EVENT_SUCCESS: "START_EVENT_SUCCESS",
  START_EVENT_FAILURE: "START_EVENT_FAILURE",

  UPDATE_HOST_PROPERTIES_CONNECT_START: "UPDATE_HOST_PROPERTIES_CONNECT_START",
  UPDATE_HOST_PROPERTIES_CONNECT_SUCCESS: "UPDATE_HOST_PROPERTIES_CONNECT_SUCCESS",
  UPDATE_HOST_PROPERTIES_CONNECT_FAILURE: "UPDATE_HOST_PROPERTIES_CONNECT_FAILURE",

  UPDATE_HOST_PROPERTIES_EVENT_START: "UPDATE_HOST_PROPERTIES_EVENT_START",
  UPDATE_HOST_PROPERTIES_EVENT_SUCCESS: "UPDATE_HOST_PROPERTIES_EVENT_SUCCESS",
  UPDATE_HOST_PROPERTIES_EVENT_FAILURE: "UPDATE_HOST_PROPERTIES_EVENT_FAILURE",
}

export default EventHostPropertiesActions
