const EventHostPropertiesActions = {
  CREATE_EVENT_START: "CREATE_EVENT_START",
  CREATE_EVENT_SUCCESS: "CREATE_EVENT_SUCCESS",
  CREATE_EVENT_FAILURE: "CREATE_EVENT_FAILURE",
}

export default EventHostPropertiesActions
