const EventHostActions = {
  CREATE_EVENT_START: "CREATE_EVENT_START",
  CREATE_EVENT_SUCCESS: "CREATE_EVENT_SUCCESS",
  CREATE_EVENT_FAILURE: "CREATE_EVENT_FAILURE",

  ON_PLAYERS_CHANGE: "ON_PLAYERS_CHANGE",
}

export default EventHostActions
