const UserActionTypes = {
  COMPLETED_AUTH_INITIAL_PROCESS: "COMPLETED_AUTH_INITIAL_PROCESS",

  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
  GOOGLE_SIGN_IN_START: "SIGN_IN_START",
  EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",

  CHECK_USER_SESSION: "CHECK_USER_SESSION",

  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",

  EMAIL_SIGN_UP_START: "EMAIL_SIGN_UP_START",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",

  TOGGLE_FAVORITE_COLLECTION_START: "TOGGLE_FAVORITE_COLLECTION_START",
  TOGGLE_FAVORITE_COLLECTION_SUCCESS: "TOGGLE_FAVORITE_COLLECTION_SUCCESS",
  TOGGLE_FAVORITE_COLLECTION_FAILURE: "TOGGLE_FAVORITE_COLLECTION_FAILURE",
}

export default UserActionTypes
